spring:
  application:
    name: activityService
  data:
    mongodb:
      url: mongodb://localhost:27017/activityCapturedData
      database: activityCapturedData
  jackson:
    serialization:
      write-dates-as-timestamps: false
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      properties:
        spring.json.add.type.headers: false
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

kafka:
  topic:
    name: activity-events-v2

server:
  port: 8082

eureka:
  client:
    serverUrl:
      defaultZone: http://localhost:8761/eureka/
