spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: userService
              uri: lb://userService
              predicates:
                - Path=/metaFitAi/users/**

            - id: activityService
              uri: lb://activityService
              predicates:
                - Path=/metaFitAi/activities

            - id: aiService
              uri: lb://aiService
              predicates:
                - Path=/metaFitAi/recommendations/**

server:
  port: 8080

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/