spring:
  application:
    name: userService
  datasource:
    url: jdbc:postgresql://localhost:5432/userData
    username: postgres
    password: admin@123

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect


