spring:
  application:
    name: userService
  datasource:
    url: jdbc:postgresql://localhost:5432/userData
    username: postgres
    password: admin@123

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081

eureka:
  instance:
    prefer-ip-address: true
  client:
    serverUrl:
      defaultZone: http://localhost:8761/eureka/


